version: '2'
services:
  web:
    build: ./nginx
    volumes:
      - "./nginx/ssl_dev:/etc/letsencrypt/live/shravocado.cc"
      - "./nginx/nginx-root:/usr/share/nginx/html"
    ports:
      - "80:80"
      - "443:443"
  backend:
    build: ./backend
    volumes: 
      - "./backend:/usr/share/backend"
    ports:
      - "8080:8080"  
