# Generated by Django 2.0.2 on 2018-03-04 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_blogpost_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='locale',
            field=models.CharField(default='en-AU', max_length=8),
            preserve_default=False,
        ),
    ]
