# Generated by Django 2.0.2 on 2018-03-07 07:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20180307_1559'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogtag',
            old_name='tag',
            new_name='name',
        ),
        migrations.AlterUniqueTogether(
            name='blogtag',
            unique_together={('post', 'name')},
        ),
    ]
